---
output: github_document
---

# psi2301

- Conjunto de funciones y datos compilados para el curso Métodos de Investigación Cuantitativa (PSI2301)


## Instalación

Para instalar la versión más actualizada de la librería en R, disponible en el repositorio [github](https://github.com/dacarras/psi2301) se puede emplear el siguiente comando:

``` r

devtools::install_github('dacarras/psi2301',force = TRUE)

```

>Nota: este comando requiere que la librería `devtools` se encuentre instalada. Para instalar remotes ocupar `install.packages('devtools')`.

# Desarollo

## Listado de funciones

- `c_mean()` calcula medias por grupo. Función incluida para crear centrado de variables.
- `get_data()` genera una muestra aleatorio de datos, de un tamaño especificado, condicional al id number del usuario.
- `mean_score()` calcula promedio de respuesta, de un conjunto de variables. Sirve para generar puntajes basados en promedios.
- `sum_score()` calcula suma de respuesta, de un conjunto de variables. Sirve para generar puntajes basados en sumas.
- `z_score()` calcula puntaje zeta de un vector o variable.
- `reverse`()` calcula el inverso de un puntaje.
- `remove_labels`()` remueve la metada de una base de datos.

# Datos

- accionescolestivas
- amistad_intergrupal
- b5
- coes_2014
- data
- dem_16
- desarollo_psicomotor
- elpi3
- homonegatividad
- iccs_09_chl
- iccs_09_lat
- iccs_16_lat
- iccs_2009
- iccs_2016
- ingresos_2016
- injuv_2012
- integracion_universitaria
- life_2000
- ptsd_data
- smoking
- terce
- terremoto

Para acceder a la descripción de los datos ejecutar `? psi23::[nombre de los datos]`, por ejemplo `? psi2301::smoking`.
